services:
  mongo1:
    image: mongo:8.0.3
    container_name: mongo1
    network_mode: host
    command: ["--replSet", "rs0", "--port", "27018", "--bind_ip", "0.0.0.0"]
    volumes:
      - mongo1_data:/data/db
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'127.0.0.1:27018',priority:1},{_id:1,host:'127.0.0.1:27019',priority:0.5},{_id:2,host:'127.0.0.1:27020',priority:0.5}]}) }" | mongosh --port 27018 --quiet
      interval: 10s
      timeout: 30s
      start_period: 5s
      retries: 50
    restart: always

  mongo2:
    image: mongo:8.0.3
    container_name: mongo2
    network_mode: host
    command: ["--replSet", "rs0", "--port", "27019", "--bind_ip", "0.0.0.0"]
    volumes:
      - mongo2_data:/data/db
    restart: always

  mongo3:
    image: mongo:8.0.3
    container_name: mongo3
    network_mode: host
    command: ["--replSet", "rs0", "--port", "27020", "--bind_ip", "0.0.0.0"]
    volumes:
      - mongo3_data:/data/db
    restart: always

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:
